import Link from "next/link";
import { AppShell, Mark } from "../components/app-shell";
import styles from "./page.module.css";

const features = [["/lock.png", "Secure & Verifiable", "Every ticket exists on Monad — immutable, transparent, and linked to its rightful owner."], ["/hands.png", "Transfer or Trade Freely", "Transfer or list your ticket directly from your wallet."], ["/computer.png", "Event Manager Dashboard", "Create events, set prices, and track sales in real time."], ["/watchtower.png", "Seamless Wallet Integration", "Connect with MetaMask, Rabby, or WalletConnect in one step."]];

export default function Home() {
  return <AppShell home><div className={styles.page}>
    <section className={`cornerAccents ${styles.hero}`}><div className={styles.heroShade} /><div className={styles.heroContent}><div className={styles.heroNav}><span className={styles.heroBrand}><Mark /> Monad Blitz</span><Link href="/discover">Get Started</Link></div><h1>Own Your Tickets.<br />Trade Them Freely.</h1></div></section>
    <section className={`cornerAccents ${styles.intro}`}><div className={styles.introCopy}><p className={styles.pill}><i /> POWERED BY MONAD</p><h2>The first truly transparent ticketing platform.</h2><p>Tickets as NFTs. No middlemen, no hidden fees, full ownership. Every transaction is verifiable on-chain.</p></div><div className={styles.metrics}><div><strong>12</strong><span>Live Events</span></div><div><strong>3.4K</strong><span>Tickets Sold</span></div><div><strong>MON</strong><span>Network</span></div></div></section>
    <section className={styles.featureGrid}>{features.map(([image, title, description]) => <article className={`cornerAccents ${styles.feature}`} key={title}><div className={styles.featureImage} style={{ backgroundImage: `url(${image})` }} /><div className={styles.featureCopy}><h3><i /> {title}</h3><p>{description}</p></div></article>)}</section>
    <section className={`cornerAccents ${styles.events}`}><div className={styles.eventsTitle}><div><h2>Explore Live Events</h2><p>Discover upcoming events on the blockchain</p></div><Link href="/discover">View All ↗</Link></div><div className={styles.eventGrid}>{["Monad Builders Night", "Onchain Art Assembly", "Monadic Sounds"].map((name, index) => <Link className={styles.eventCard} href="/discover" key={name}><div className={styles.eventImage} data-index={index}>MONAD<br />BLITZ</div><div className={styles.eventMeta}><b>ON SALE</b><time>OCT {19 + index * 4}</time></div><h3>{name}</h3><p>0.05 MON <span>· {80 - index * 15}/100 available</span></p></Link>)}</div></section>
    <section className={`cornerAccents ${styles.launch}`}><div><h2>Launch Your Event in Minutes</h2><p>Create tickets, set prices and define royalties. Watch sales happen live on-chain with zero hassle.</p><div className={styles.launchStats}><span><b>5 min</b>Setup Time</span><span><b>0%</b>Hidden Fees</span><span><b>100%</b>Your Control</span></div><Link href="/create">Create Your Event ↗</Link></div><aside><div><b>ACTIVITY</b><span><i /> LIVE</span></div><p>New activity will appear here.</p></aside></section>
  </div></AppShell>;
}
