import Link from "next/link";
import { AppShell, Mark } from "../components/app-shell";
import styles from "./page.module.css";

const features = [["/lock.png", "Güvenli ve doğrulanabilir", "Her bilet Monad üzerinde değiştirilemez, şeffaf ve sahibine bağlıdır."], ["/hands.png", "Özgürce transfer et veya sat", "Biletini cüzdanın üzerinden doğrudan devret ya da listele."], ["/computer.png", "Etkinlik yönetim paneli", "Etkinlik oluştur, fiyat belirle ve satışları gerçek zamanlı takip et."], ["/watchtower.png", "Kolay cüzdan bağlantısı", "MetaMask, Rabby ve WalletConnect ile tek adımda devam et."]];

export default function Home() {
  return <AppShell home><div className={styles.page}>
    <section className={`cornerAccents ${styles.hero}`}><div className={styles.heroShade} /><div className={styles.heroContent}><div className={styles.heroNav}><span className={styles.heroBrand}><Mark /> Monad Blitz</span><Link href="/discover">Başla</Link></div><h1>Biletlerin senin.<br />Özgürce kullan.</h1></div></section>
    <section className={`cornerAccents ${styles.intro}`}><div className={styles.introCopy}><p className={styles.pill}><i /> MONAD İLE GÜÇLENDİRİLDİ</p><h2>Gerçekten şeffaf ilk biletleme platformu.</h2><p>Biletler NFT olarak zincir üzerinde yaşar. Aracı yok, gizli ücret yok, tam sahiplik var. Her işlem doğrulanabilir.</p></div><div className={styles.metrics}><div><strong>12</strong><span>Canlı etkinlik</span></div><div><strong>3.4K</strong><span>Satılan bilet</span></div><div><strong>MON</strong><span>Ağ</span></div></div></section>
    <section className={styles.featureGrid}>{features.map(([image, title, description]) => <article className={`cornerAccents ${styles.feature}`} key={title}><div className={styles.featureImage} style={{ backgroundImage: `url(${image})` }} /><div className={styles.featureCopy}><h3><i /> {title}</h3><p>{description}</p></div></article>)}</section>
    <section className={`cornerAccents ${styles.events}`}><div className={styles.eventsTitle}><div><h2>Canlı etkinlikleri keşfet</h2><p>Zincir üzerindeki yaklaşan etkinlikleri incele</p></div><Link href="/discover">Tümünü gör ↗</Link></div><div className={styles.eventGrid}>{["Monad Builders Night", "Onchain Art Assembly", "Monadic Sounds"].map((name, index) => <Link className={styles.eventCard} href="/discover" key={name}><div className={styles.eventImage} data-index={index}>MONAD<br />BLITZ</div><div className={styles.eventMeta}><b>Satışta</b><time>{19 + index * 4} EKİM</time></div><h3>{name}</h3><p>0.05 MON <span>· {80 - index * 15}/100 mevcut</span></p></Link>)}</div></section>
    <section className={`cornerAccents ${styles.launch}`}><div><h2>Etkinliğini dakikalar içinde başlat</h2><p>Biletleri oluştur, fiyatı ve telif oranını belirle. Satışları zincir üzerinde zahmetsizce takip et.</p><div className={styles.launchStats}><span><b>5 dk</b>Kurulum süresi</span><span><b>0%</b>Gizli ücret</span><span><b>100%</b>Senin kontrolün</span></div><Link href="/create">Etkinlik oluştur ↗</Link></div><aside><div><b>AKTİVİTE</b><span><i /> CANLI</span></div><p>Yeni işlemler burada görünecek.</p></aside></section>
  </div></AppShell>;
}
