import Link from "next/link";
import { AppShell, Icon } from "../components/app-shell";
import styles from "./page.module.css";

const highlights = [["12", "Yaklaşan etkinlik"], ["3.4K", "Benzersiz bilet"], ["0%", "Platform komisyonu"]];
const events = [["LIVE\nNOW", "19 EKİM · İSTANBUL", "Monadic Sounds", "0.08 MON", "purple"], ["BUILD\nFAST", "25 EKİM · İSTANBUL", "Monad Builders Night", "Ücretsiz", "orange"], ["ART\nONCHAIN", "02 KASIM · ANKARA", "Digital Art Assembly", "0.04 MON", "blue"]];

export default function Home() {
  return <AppShell><section className={styles.hero}><div className={styles.heroCopy}><p className={styles.eyebrow}><span /> Monad üzerinde biletleme</p><h1>Unutulmayacak<br /><em>anlar</em> için biletler.</h1><p className={styles.description}>Etkinlikleri keşfet, biletini zincir üzerinde al ve her anı koleksiyonunun bir parçası yap.</p><div className={styles.heroActions}><Link className={styles.primaryAction} href="/events">Etkinlikleri keşfet <span>→</span></Link><Link className={styles.secondaryAction} href="/create"><Icon name="plus" size={17} /> Etkinlik oluştur</Link></div></div><div className={styles.art} aria-label="Monad Blitz bilet görseli"><div className={styles.orbitOne} /><div className={styles.orbitTwo} /><div className={styles.ticket}><div className={styles.ticketTop}><span>MONAD BLITZ</span><span>01</span></div><div className={styles.ticketTitle}>YOUR NEXT<br />MOMENT</div><div className={styles.ticketFoot}><span>MONAD TESTNET</span><span>✦</span></div></div><div className={styles.spark}>✦</div></div></section><section className={styles.stats} aria-label="Monad Blitz istatistikleri">{highlights.map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</section><section className={styles.discovery}><div className={styles.sectionHeading}><div><p className={styles.kicker}>KEŞFET</p><h2>Senin için seçtiklerimiz</h2></div><Link href="/events">Tüm etkinlikler <span>→</span></Link></div><div className={styles.categoryRow}>{["Müzik", "Teknoloji", "Sanat", "Spor", "Topluluk"].map((category, index) => <button className={index === 0 ? styles.activeCategory : ""} type="button" key={category}>{category}</button>)}</div><div className={styles.previewGrid}>{events.map(([art, date, title, price, color]) => <article className={styles.eventPreview} key={title}><div className={`${styles.eventArt} ${styles[color]}`}>{art.split("\n").map((line) => <span key={line}>{line}<br /></span>)}</div><p>{date}</p><h3>{title}</h3><span>{price}</span></article>)}</div></section></AppShell>;
}
