"use client";

import { useState, type FormEvent } from "react";
import { AppShell } from "@/components/app-shell";
import styles from "../portal.module.css";

const initial = { name: "", description: "", startsAt: "", venue: "", category: "Music", supply: "100", price: "0.05", image: "/lock.png" };

export default function CreateEventPage() {
  const [form, setForm] = useState(initial); const [message, setMessage] = useState(""); const [submitting, setSubmitting] = useState(false); const [uploading, setUploading] = useState(false);
  const set = (key: keyof typeof initial, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitting(true); setMessage(""); try { const response = await fetch("/api/events/drafts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json() as { data?: { id: string }; error?: string }; setMessage(response.ok ? `Event draft ${body.data?.id} is ready. Deploy it after the Monad factory address is available.` : body.error ?? "Unable to create event draft."); if (response.ok) setForm(initial); } finally { setSubmitting(false); } }
  async function uploadImage(file: File) { setUploading(true); try { const payload = new FormData(); payload.set("file", file); const response = await fetch("/api/ipfs/upload", { method: "POST", body: payload }); const body = await response.json() as { data?: { uri: string }; error?: string }; if (!response.ok) return setMessage(body.error ?? "Unable to upload image."); set("image", body.data!.uri); setMessage("Image pinned to IPFS and attached to this event draft."); } finally { setUploading(false); } }
  return <AppShell><div className={styles.page}><section className={`cornerAccents ${styles.hero}`}><div className={styles.heroCopy}><p className={styles.eyebrow}>[EVENT_CREATOR]</p><h1>Create Event</h1><p>Prepare ticket metadata and event settings for a Monad deployment.</p></div><div className={styles.stats}><div><b>0%</b><span>Platform Fee</span></div><div><b>MON</b><span>Payment Token</span></div></div></section><form className={`cornerAccents ${styles.panel}`} onSubmit={submit}><div className={styles.sectionHead}><h2>[EVENT_DETAILS]</h2><span>REQUIRED FIELDS *</span></div><div className={styles.formGrid}><label>Event name<input required value={form.name} onChange={(e) => set("name", e.target.value)} placeholder="Enter event name" /></label><label>Category<select value={form.category} onChange={(e) => set("category", e.target.value)}><option>Music</option><option>Conference</option><option>Sports</option><option>Art</option><option>Theater</option><option>Festival</option></select></label><label className={styles.full}>Description<textarea required minLength={20} value={form.description} onChange={(e) => set("description", e.target.value)} placeholder="Describe your event" /></label><label className={styles.full}>Event image<input accept="image/*" onChange={(event) => event.target.files?.[0] && void uploadImage(event.target.files[0])} type="file" />{uploading ? "Pinning image…" : form.image.startsWith("ipfs://") ? "Pinned to IPFS" : "PNG, JPG, WebP up to 5 MB"}</label><label>Start date and time<input required type="datetime-local" value={form.startsAt} onChange={(e) => set("startsAt", e.target.value)} /></label><label>Venue<input required value={form.venue} onChange={(e) => set("venue", e.target.value)} placeholder="Venue, city" /></label><label>Ticket supply<input required type="number" min="1" value={form.supply} onChange={(e) => set("supply", e.target.value)} /></label><label>Ticket price (MON)<input required type="number" step="0.01" min="0.01" value={form.price} onChange={(e) => set("price", e.target.value)} /></label></div><div className={styles.form}><button className={styles.primary} disabled={submitting || uploading} type="submit">{submitting ? "Preparing..." : "Prepare Event Deployment"}</button></div>{message && <p className={styles.result}>{message}</p>}</form></div></AppShell>;
}
